import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import pg from 'pg';
import {ContactAccessService,ensureContactAccessSchema} from '../../server/contactAccessService';
import {importInvoiceDirectory} from '../../server/invoiceDirectoryImport';

test('contact review: concurrent duplicates, approval, refusal, distinct identity, revocation and tenant isolation',async()=>{
  const url=process.env.CONTACT_ACCESS_TEST_DATABASE_URL;
  assert.ok(url && (new URL(url).hostname==='db' || (process.env.CI==='true' && new URL(url).hostname==='127.0.0.1' && new URL(url).pathname==='/visit_manager_test')),'Only the isolated Docker/CI database is allowed');
  const schema='access_test_'+crypto.randomBytes(8).toString('hex');
  const setup=new pg.Pool({connectionString:url});
  const pool=new pg.Pool({connectionString:url,options:'-c search_path='+schema});
  try {
    await setup.query(`CREATE SCHEMA ${schema}`);
    await pool.query(`CREATE TABLE empresas(id varchar PRIMARY KEY);
      CREATE TABLE users(id varchar PRIMARY KEY,empresa_id varchar,role text,ativo boolean);
      CREATE TABLE entidade_tipos(id varchar PRIMARY KEY,empresa_id varchar);
      CREATE TABLE entidades(id varchar PRIMARY KEY,empresa_id varchar,nome text,email text,telefone text,nif text,country_code text,website text,created_by_user_id varchar,notas text,entidade_tipo_id varchar,proximity_alerts_enabled boolean);
      CREATE TABLE contactos(id varchar PRIMARY KEY,empresa_id varchar,nome text,email text,telemovel text,created_by_user_id varchar,funcao text,observacoes text,entidade_id varchar);
      INSERT INTO empresas VALUES('a'),('b');
      INSERT INTO entidade_tipos VALUES('type-a','a'),('type-b','b');
      INSERT INTO users VALUES('admin','a','admin',true),('agent','a','agent',true),('other','a','agent',true),('outsider','b','admin',true);`);
    await ensureContactAccessSchema(pool);
    await ensureContactAccessSchema(pool);
    const service=new ContactAccessService(pool);
    const sourceEntity={id:'clean-entity',partner_id:null,legal_name:'Clean SA',trading_name:'',tax_id:'501111111',country_code:'PT',email:'clean@example.test',phone:'',website:'',status:'active',updated_at:'2026-10-02'};
    const sourcePerson={id:'clean-person',full_name:'Clean Contact',email:'person@example.test',phone:'211234567',mobile:'912345670',status:'active',updated_at:'2026-10-02'};
    const sourceAssignment={id:'clean-link',entity_id:'clean-entity',contact_id:'clean-person',job_title:'',department:'',is_primary:1,status:'active'};
    const snapshot={entities:[sourceEntity,{...sourceEntity,id:'clean-entity-2',legal_name:'Clean B'}],contacts:[sourcePerson],
      assignments:[sourceAssignment,{...sourceAssignment,id:'clean-link-2',entity_id:'clean-entity-2'}]};
    assert.deepEqual(await importInvoiceDirectory(pool,'a',snapshot),{entities:2,contacts:1,assignments:2});
    const sourceId=(await pool.query("SELECT local_id FROM invoice_directory_records WHERE kind='person'")).rows[0].local_id;
    assert.deepEqual((await pool.query("SELECT source_data FROM invoice_directory_records WHERE kind='person'")).rows[0].source_data,sourcePerson,'both phone numbers and source fields survive import');
    await assert.rejects(importInvoiceDirectory(pool,'a',snapshot,'another-workspace'),(e:any)=>e.status===409);
    assert.equal((await pool.query("SELECT identity FROM invoice_directory_sources WHERE empresa_id='a'")).rows[0].identity,'local-test');
    assert.equal(await service.allowed('agent','person',sourceId),false,'import must not grant access');
    const alternatePhone=await service.submit('agent',{kind:'person',name:'Different display name',phone:'211234567'});
    assert.equal(alternatePhone.state,'pending','landline match must require approval even when the primary number is mobile');
    await service.decide('admin',alternatePhone.requestId!,'reject');
    await service.grant('admin','agent','person',sourceId,'granted');
    await importInvoiceDirectory(pool,'a',snapshot);
    assert.equal((await pool.query("SELECT local_id FROM invoice_directory_records WHERE kind='person'")).rows[0].local_id,sourceId);
    assert.equal(await service.allowed('agent','person',sourceId),true);
    assert.equal((await service.list('agent','person')).find(r=>r.id===sourceId)?.alternativePhone,'211234567');
    const before=(await pool.query('SELECT count(*) FROM contactos')).rows[0].count;
    await assert.rejects(importInvoiceDirectory(pool,'a',{...snapshot,contacts:[sourcePerson,{...sourcePerson,id:'new'}],
      assignments:[{...sourceAssignment,contact_id:'missing'}]}),/Associação sem contacto/);
    assert.equal((await pool.query('SELECT count(*) FROM contactos')).rows[0].count,before,'failed import rolls back all rows');
    assert.equal((await pool.query('SELECT count(*) FROM invoice_directory_assignments')).rows[0].count,'2');
    await importInvoiceDirectory(pool,'a',{...snapshot,contacts:[{...sourcePerson,status:'archived'}]});
    assert.equal(await service.allowed('agent','person',sourceId),false,'inactive source cancels effective access');
    assert.equal((await service.list('agent','person')).some(r=>r.id===sourceId),false);
    assert.equal((await service.list('admin','person')).some(r=>r.id===sourceId),true,'admin can review inactive source contacts');
    await importInvoiceDirectory(pool,'a',snapshot);
    const body={kind:'person',name:'Ana Silva',email:'ana@example.test',phone:'912345678'};
    const first=await service.submit('admin',body);
    assert.equal(first.state,'created');
    const id=first.id!;
    assert.equal(await service.allowed('agent','person',id),false);
    const pending=await Promise.all([service.submit('agent',body),service.submit('agent',body)]);
    assert.equal(pending[0].requestId,pending[1].requestId);
    assert.deepEqual(Object.keys(pending[0]).sort(),['requestId','state']);
    const own=await service.requests('agent');
    assert.equal(own.filter(r=>r.state==='pending').length,1); assert.equal('candidates' in own[0],false);
    assert.equal((await service.requests('outsider')).length,0);
    assert.equal((await service.requests('admin'))[0].candidates[0].id,id);
    await assert.rejects(service.decide('agent',pending[0].requestId!,'approve',id),(e:any)=>e.status===403);
    await assert.rejects(service.decide('outsider',pending[0].requestId!,'approve',id),(e:any)=>e.status===404);
    await assert.rejects(service.decide('admin',pending[0].requestId!,'approve','forged'),(e:any)=>e.status===400);
    await service.decide('admin',pending[0].requestId!,'approve',id);
    assert.equal(await service.allowed('agent','person',id),true);
    assert.equal(await service.allowed('agent','entity',id),false);
    assert.equal(await service.allowed('other','person',id),false);
    await service.grant('admin','agent','person',id,'revoked');
    assert.equal(await service.allowed('agent','person',id),false);
    await assert.rejects(service.grant('admin','outsider','person',id,'granted'),(e:any)=>e.status===403);
    await assert.rejects(service.decide('admin',pending[0].requestId!,'approve',id),(e:any)=>e.status===409);
    const retry=await service.submit('agent',body);
    await service.decide('admin',retry.requestId!,'reject');
    assert.equal(await service.allowed('agent','person',id),false);
    const distinct=await service.submit('agent',{kind:'person',name:'Ana Silva',email:'different@example.test'});
    const separate=await service.decide('admin',distinct.requestId!,'distinct');
    assert.notEqual(separate.id,id);
    assert.equal(await service.allowed('agent','person',separate.id!),true);
    await service.grant('admin','agent','person',separate.id!,'revoked');
    assert.equal(await service.allowed('agent','person',separate.id!),false,'revocation overrides creator access');
    const concurrent=await Promise.all([service.submit('agent',{kind:'entity',name:'New SA',taxId:'PT501234567'}),service.submit('other',{kind:'entity',name:'New SA',taxId:'501234567'})]);
    assert.deepEqual(concurrent.map(r=>r.state).sort(),['created','pending']);
    const entityReview=await service.submit('agent',{kind:'entity',name:'New SA',entityTypeId:'type-a',proximityAlertsEnabled:true});
    const separateEntity=await service.decide('admin',entityReview.requestId!,'distinct');
    assert.deepEqual((await pool.query('SELECT entidade_tipo_id,proximity_alerts_enabled FROM entidades WHERE id=$1',[separateEntity.id])).rows[0],{entidade_tipo_id:'type-a',proximity_alerts_enabled:true});
    await assert.rejects(service.submit('agent',{kind:'entity',name:'Different new entity',entityTypeId:'type-b'}),(e:any)=>e.status===404);
    await pool.query("UPDATE users SET role='agent' WHERE id='admin'");
    await assert.rejects(service.grant('admin','agent','person',id,'granted'),(e:any)=>e.status===403,'fresh database role is required');
    await pool.query("UPDATE users SET ativo=false WHERE id='agent'");
    await assert.rejects(service.requests('agent'),(e:any)=>e.status===401);
    await pool.query("UPDATE users SET role='unexpected' WHERE id='other'");
    await assert.rejects(service.requests('other'),(e:any)=>e.status===401);
    assert.ok(Number((await pool.query('SELECT count(*) FROM contact_access_audit')).rows[0].count)>=8);
  } finally {
    await pool.end();
    await setup.query(`DROP SCHEMA ${schema} CASCADE`);
    await setup.end();
  }
});
